// src/app/layout.tsx
import type { Metadata } from "next";
import "./style/globals.css";
import { LanguageProvider } from "../contexts/LanguageContext"; // ייבוא של LanguageProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
