title: My Awesome Site
description: A description of my awesome site.
baseurl: ""
url: "https://www.topmarket10.com"

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10

exclude:
  - node_modules
